### ISSUE TITLE
AttributeError: 'str' object has no attribute 'ip'

### ISSUE THREAD

**Issue by IIPoliII** [priyamharsh14/SniffnDetect#4]
Hey,
It looks like a very interesting project but sadly when I run 
`sudo python3 app.py`
I get the following
```
~/SniffnDetect# sudo python3 app.py
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    sniffer = SniffnDetect()
  File "/root/SniffnDetect/sniffndetect.py", line 16, in __init__
    self.MY_IP = self.INTERFACE.ip
AttributeError: 'str' object has no attribute 'ip'
```

Any idea why? Thanks for your help.

**Comment by priyamharsh14** [comment]
Let me check and get back to you.

**Comment by priyamharsh14** [comment]
Ok, this is a valid issue. Thanks for notifying me. During the UI update, I removed the code by mistake which extracts IP and other info from the interface (for LINUX machine). Current code is working on Windows, but not on Linux.

I will push an update ASAP to fix it.

Thanks again @IIPoliII

**Comment by priyamharsh14** [comment]
@IIPoliII Please check the updated code and let me know.
Thanks.

**Comment by Taguar258** [comment]
I also ran into the issue of self.INTERFACE.name not found, I don't know if I did something wrong.
